"    ____         .__
"   / ___\ ___  __|__|  _____ _______   ____
"  / /_/  >\  \/ /|  | /     \\_  __ \_/ ___\
"  \___  /  \   / |  ||  Y Y  \|  | \/\  \___
" /_____/    \_/  |__||__|_|  /|__|    \___  >
"                           \/             \/
" FIGMENTIZE: gvimrc

" GVimrc that tries to make gvim look at much like my terminal as possible.

" Set some generic font for GVim, particularly we care about the font size.
" Only set it once because for some reason the screen messes itself up if you
" set it again.
command ResetFont set guifont=Liberation\ Mono\ for\ Powerline\ 12

if (!exists("g:goedel_set_font")) || !g:goedel_set_font
    ResetFont
    let g:goedel_set_font=1
endif

" set toolbar+=text
" set toolbariconsize=tiny

" binding to change font size
nnoremap <Leader>f :set guifont=*<CR>

" TODO: maybe add some yo- toggles
" same as default guioptions, but without tabs, scrollbars, menus or toolbars.
set guioptions=agiLtc
" same as default options but turn off blinking
set guicursor=n-v-c:block-Cursor/lCursor-blinkon0,ve:ver35-Cursor-blinkon0,o:hor50-Cursor-blinkon0,i-ci:ver25-Cursor/lCursor-blinkon0,r-cr:hor20-Cursor/lCursor-blinkon0,sm:block-Cursor-blinkon0

" allow the use of select mode, which is more like a Microsoft windows
" selection.
set selectmode=mouse,key

" set transparency if possible
if executable("transset-df")
    " this would automatically set transparency. Disable for now
    " augroup GVimTransset
    "     autocmd! GuiEnter * silent exec "!transset-df -a 0.97"
    " augroup END
    " remap this to work with a proper non-terminal
    " mnemonic: toggle Transparency
    nnoremap yot :silent exec "!transset-df -a -t 0.97"<CR><C-L>
endif

" basically, because gvim is supposed to be the friendly one
unmap <Left>
unmap <Right>
unmap <Up>
unmap <Down>
" because these aren't mapped, but are needed for temporary mappings with
" ultisnips
" iunmap <Left>
" iunmap <Right>
iunmap <Up>
iunmap <Down>
