if v:progname =~? "evim"
  finish
endif

execute pathogen#infect()

if &compatible | set nocompatible | endif " Avoid side effects if `nocp` already set
set backspace=indent,eol,start
set history=50
set ruler
set showcmd
set incsearch
if &t_Co > 2 || has("gui_running")
  syntax on
  set hlsearch
  syntax enable
  let g:solarized_termtrans = 1
  set background=dark
  colorscheme solarized
endif
set autoindent
if has('langmap') && exists('+langnoremap')
  set langnoremap
endif
packadd matchit

set tabstop=4
set shiftwidth=4
set ignorecase
set infercase
set expandtab
set hlsearch
set incsearch
" backspace key fix?
set t_kb=
set cryptmethod=blowfish2
set textwidth=80
set colorcolumn=+1
set mouse=a
map <LeftMouse> <nop>

set path+=**
set wildmenu

set list
set listchars=tab:>-

highlight ExtraWhitespace ctermbg=darkgreen guibg=darkgreen
autocmd ColorScheme * highlight ExtraWhitespace ctermbg=red guibg=red
match ExtraWhitespace /\s\+$/

" Persistent undo
set undofile
set undodir=$HOME/.vim/undo

set undolevels=1000
set undoreload=10000

" '100: store marks for 100 previously edited files
" /100: store 100 previous searches
" :100: store 100 previous commands issued
" <1000000: store at most 1000000 lines of each buffer
" @1000: store 1000 lineso f input-line history
" s1000: allow items to be 10000 Kbyte in size
set viminfo=%,'100,/100,:100,<1000000,s10000,@1000,h,n~/.vim/viminfo

autocmd FileType make setlocal noexpandtab

" Allow saving of files as sudo when I forgot to start vim using sudo.
command W w !sudo tee > /dev/null %
