#!/usr/bin/env bash

# Need bash for fancy parameter expansion

for file; do
    if [ -f "$file" ]; then
        dest_file="${file//%/%%}"
        dest_file="./etc/${dest_file//\//%s}"
        cp "$file" "$dest_file"
    else
        >&2 echo "can't copy $file"
    fi
done
