#!/usr/bin/env bash

# Need bash for fancy parameter expansion

for file; do
    if [ -f "$file" ]; then
        dest_file="./etc/$file"
        mkdir -p "$(dirname "$dest_file")"
        cp "$file" "$dest_file"
    else
        >&2 echo "can't copy $file"
    fi
done
