
if [[ "$GOEDEL_COLORSCHEME" == light ]]; then
    POWERLEVEL9K_COLOR_SCHEME='light'
else
    POWERLEVEL9K_COLOR_SCHEME='dark'
fi

# customisation options for powerline. The implementation I use is
# powerlevel10k as it's a lot faster.

function p9k_shlvl_prompt {
    print -P "%(2L.%L.)"
}

POWERLEVEL9K_CUSTOM_SHLVL="p9k_shlvl_prompt"
POWERLEVEL9K_CUSTOM_SHLVL_BACKGROUND=yellow

POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS=(status custom_shlvl background_jobs history)
POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=(context root_indicator dir_writable dir vcs)

POWERLEVEL9K_ROOT_ICON=!
POWERLEVEL9K_ROOT_INDICATOR_FOREGROUND=yellow
POWERLEVEL9K_ROOT_INDICATOR_BACKGROUND=red
POWERLEVEL9K_CONTEXT_DEFAULT_BACKGROUND=yellow
POWERLEVEL9K_CONTEXT_SUDO_BACKGROUND=red
POWERLEVEL9K_CONTEXT_ROOT_BACKGROUND=red
POWERLEVEL9K_CONTEXT_REMOTE_BACKGROUND=green
POWERLEVEL9K_CONTEXT_REMOTE_SUDO_BACKGROUND=magenta
POWERLEVEL9K_CONTEXT_DEFAULT_FOREGROUND=black
POWERLEVEL9K_CONTEXT_SUDO_FOREGROUND=yellow
POWERLEVEL9K_CONTEXT_ROOT_FOREGROUND=yellow
POWERLEVEL9K_CONTEXT_REMOTE_FOREGROUND=black
# POWERLEVEL9K_CONTEXT_SUDO_BOLD=true
# POWERLEVEL9K_CONTEXT_ROOT_BOLD=true
POWERLEVEL9K_CONTEXT_REMOTE_SUDO_FOREGROUND=black
POWERLEVEL9K_HISTORY_BACKGROUND=blue
# red and green, of course
POWERLEVEL9K_CONTEXT_REMOTE_SUDO_BACKGROUND=magenta
# BLOAT IS NOT WELCOMe HERE
# POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS=(status background_jobs history time battery)
# I try to use just the colours 1-8 so that they change along with colour
# schemes.
POWERLEVEL9K_BATTERY_LOW_FOREGROUND='black'
POWERLEVEL9K_BATTERY_CHARGING_FOREGROUND='black'
POWERLEVEL9K_BATTERY_CHARGED_FOREGROUND='black'
POWERLEVEL9K_BATTERY_DISCONNECTED_FOREGROUND='black'
POWERLEVEL9K_BATTERY_LEVEL_BACKGROUND=(red3 darkorange3 darkgoldenrod gold3 yellow3 chartreuse2 mediumspringgreen green3 green3 green4 darkgreen)
POWERLEVEL9K_BATTERY_STAGES="▁▂▃▄▅▆▇█"
# show current vi mode in prompt
POWERLEVEL9K_VI_INSERT_MODE_STRING='I'
POWERLEVEL9K_VI_COMMAND_MODE_STRING='N'
# POWERLEVEL9K_VI_VISUAL_MODE_STRING='V'
POWERLEVEL9K_VI_MODE_INSERT_BACKGROUND=cyan
POWERLEVEL9K_VI_MODE_INSERT_FOREGROUND=cyan
POWERLEVEL9K_VI_MODE_NORMAL_BACKGROUND=magenta
POWERLEVEL9K_VI_MODE_NORMAL_FOREGROUND=magenta
POWERLEVEL9K_PROMPT_ON_NEWLINE=true
POWERLEVEL9K_RPROMPT_ON_NEWLINE=true
POWERLEVEL9K_PROMPT_ADD_NEWLINE=true
# this is a weird little hack I wrote to colour other bits of my prompt
# according to the current keymap, as it seems that p9k exposes the KEYMAP
# to the prompt
GOEDEL_P9K_VI_COLOUR='$(case "$KEYMAP" in vicmd) echo magenta;; main|viins|) echo cyan;; *) echo white;; esac)'
POWERLEVEL9K_MULTILINE_FIRST_PROMPT_PREFIX="%F{$GOEDEL_P9K_VI_COLOUR}╔═%f"
    POWERLEVEL9K_MULTILINE_LAST_PROMPT_PREFIX="%F{$GOEDEL_P9K_VI_COLOUR}╚═%f "
source "$POWERLEVEL_THEME"
PROMPT2=".. "
RPROMPT2="%_"
